// task10-vue/one-piece-site/src/components/cards/IslandCard.vue
<template>
  <div className="island-card">
    <img className="card-grid__img" :src=image alt=""/>
    <div className="island-card__infobox">
      <p className="l3">{name}</p>
      <p className="p-small"><i className="fa-solid fa-location-dot"></i> {location}</p>
    </div>
  </div>
</template>


<script>
  export default {
    name : "IslandCard",
    props : {
      name : String,
      image : String,
      location : String,
    }
  }
</script>

// task09-reactjs/my-app/src/components/cards/IslandCard.js
import React from 'react'

const IslandCard = ({image, name, location}) => {
  return (
    <div className="island-card">
      <img className="card-grid__img" src={`images/${image}`} alt=""/>
      <div className="island-card__infobox">
        <p className="l3">{name}</p>
        <p className="p-small"><i className="fa-solid fa-location-dot"></i> {location}</p>
      </div>
    </div>
  )
}

export default IslandCard;
