// task10-vue/one-piece-site/src/components/cards/MysticCard.vue
<template>
  <div class="mist-grid__card">
    <img :src=image alt=""/>
    <div class="mist-grid__card-infobox">
      <p class="l3">{{name}}</p>
      <p class="p-small">{{description}}</p>
    </div>
  </div>
</template>


<script>
  export default {
    name : "MysticCard",
    props : {
      name : String, 
      description : String,
      image : String,
    }
  }
</script>

// task09-reactjs/my-app/src/components/cards/MysticCard.js
import React from 'react'

const MysticCard = ({image, name, description}) => {
  return (
    <div class="mist-grid__card">
      <img src={`images/${image}`} alt=""/>
      <div class="mist-grid__card-infobox">
        <p class="l3">{name}</p>
        <p class="p-small">{description}</p>
      </div>
    </div>
  )
}

export default MysticCard;
