// task09-reactjs/my-app/src/components/Footer.js
import React from 'react'

class Footer extends React.Component {

  render () {
    return (
      <>
      <footer>
        <img src="images/placeholder.svg" alt="" />
        <p class="p-small footer__text-container">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Velit at vel congue scelerisque tortor tortor.
        </p>
      </footer>
      </>
    )
  }
}

export default Footer;

// task10-vue/one-piece-site/src/components/Footer.vue
<template>
  <footer>
    <img src="images/placeholder.svg" alt="" />
    <p class="p-small footer__text-container">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Velit at vel congue scelerisque tortor tortor.
    </p>
  </footer>
</template>

<script>
export default {
  name: 'Footer',
}
</script>
