// task09-reactjs/my-app/src/components/Main.js
import React from 'react'
import CardGrid from './CardGrid';
import MainSection from './MainSection';

class Main extends React.Component {

  constructor() {
    super();
    this.state = {
      islands : [],
      characters : [],
      mysticObjects : []
    };
    this.URL = 'https://static.akurey.com/trainings/OnePieceInformation.json';
  }

  componentDidMount () {
    fetch( this.URL )
    .then( response => response.json() )
    .then( response => {
      response.characters.sort(this.sortByName);
      response.islands.sort(this.sortByName);
      response.mysticObjects.sort(this.sortByName);
      this.setState(response);
    })
    .catch((e) => console.error('Something went wrong while fetching data from '+this.URL+'. See error below:\n'+ e))
  }

  sortByName = (object1, object2) => {
    let name1 = object1.name.toLowerCase();
    let name2 = object2.name.toLowerCase();
    if (name1 < name2) {return -1;}
    if (name1 > name2) {return 1;}
    return 0;
  };

  render () {    
    return (
      <>
      {/* <!-- characters --> */}
      <MainSection title="Characters" to="/characters" />
      <CardGrid type="character" items={this.state.characters.slice(0,4)}/>
      {/* <!-- islands --> */}
      <MainSection title="Islands" to="/islands" />
      <CardGrid type="island" items={this.state.islands.slice(0,3)}/>
      {/* <!-- mist objects --> */}
      <MainSection title="Mystic objects" to="/mysticObjects" />
      <CardGrid type="mystic" items={this.state.mysticObjects.slice(0,4)}/>
      </>
    )
  }
}

export default Main;

// task10-vue/one-piece-site/src/components/Main.vue
<template>
  <div> 
    <!-- characters -->
    <MainSection title="Characters" to="/characters" />
    <CardGrid type="character" :items=data.characters.slice(0,4) />
    <!-- islands -->
    <MainSection title="Islands" to="/islands" />
    <CardGrid type="island" :items=data.islands.slice(0,3) />
    <!-- mist objects -->
    <MainSection title="Mystic objects" to="/mysticObjects" />
    <CardGrid type="mystic" :items=data.mysticObjects.slice(0,4) />
  </div>
</template>

<script>
import MainSection from './MainSection.vue'
import CardGrid from './cards/CardGrid.vue'
import axios from 'axios';

export default {
  name : 'Main',
  components : {
    MainSection,
    CardGrid,
  },
  methods : {
    sortByName : function (object1, object2) {
      let name1 = object1.name.toLowerCase();
      let name2 = object2.name.toLowerCase();
      if (name1 < name2) {return -1;}
      if (name1 > name2) {return 1;}
      return 0;
    },
  },
  data () {
    return {
      data : {
        characters : [],
        islands : [],
        mysticObjects : []
      },
    }
  },
  created () {
    axios
      .get('https://static.akurey.com/trainings/OnePieceInformation.json')
      .then( response => {
        this.data = response.data;
        this.data.characters.sort(this.sortByName);
        this.data.islands.sort(this.sortByName);
        this.data.mysticObjects.sort(this.sortByName);
      })
      .catch((e) => console.error('Something went wrong while fetching data from '+this.URL+'. See error below:\n'+ e))
  }
}
</script>
