// task09-reactjs/my-app/src/components/CardGrid.js
import React from 'react'
import CharacterCard from './cards/CharacterCard';
import IslandCard from './cards/IslandCard';
import MysticCard from './cards/MysticCard';

const CardGrid = ({type, items}) => {

  const switchCard = (type) => {
    switch (type) {
      case "character":
        return (
          <div className="card-grid side-padding" >
            {items.map(item => { return (<CharacterCard key={item.name} image={item.img} name={item.name}/>) })}
          </div>
        )
      case "island":
        return (
          <div className="card-grid side-padding" >
            {items.map(item => { return (<IslandCard key={item.name} image={item.img} name={item.name} location={item.Location}/>) })}
          </div>
        )
      default:
        return (
          <div className="mist-grid side-padding">
            {items.map(item => { return (<MysticCard key={item.name} image={item.img} name={item.name} description={item.description}/>) })}
          </div>
        )
    }
  }

  return (
    <>
      {items && items.length !== 0 && ( switchCard(type) )}           
    </>
  )
}



export default CardGrid;

// task10-vue/one-piece-site/src/components/cards/CardGrid.vue
<template>
<div>
  <div class="card-grid side-padding" v-if="type === 'character'">
    <CharacterCard image=""/>
    <!-- {items.map(item => { return (<CharacterCard key={item.name} image={item.img} name={item.name}/>) })} -->
  </div>

  <div class="card-grid side-padding" v-else-if="type === 'island'">
    <!-- {items.map(item => { return (<IslandCard key={item.name} image={item.img} name={item.name} location={item.Location}/>) })} -->
  </div>

  <div class="mist-grid side-padding" v-else>
    <!-- {items.map(item => { return (<MysticCard key={item.name} image={item.img} name={item.name} description={item.description}/>) })} -->
  </div>
</div>
</template>


<script>
  import CharacterCard from './CharacterCard.vue'
  import IslandCard from './IslandCard.vue'
  import MysticCard from './MysticCard.vue'

  export default {
    name : "CardGrid",
    components : {
      CharacterCard,
      IslandCard,
      MysticCard,
    },
    props : {
      type : String,
    }
  }
</script>
