// task09-reactjs/my-app/src/components/cards/CharacterCard.js
import React from 'react'

const CharacterCard = ({image, name}) => {

  const monkey_img = "img--center"
  const nico_img = "img--nico"
  const portgas_img = "img--portgas"  

  return (
    <div className={"character-card"}>
      <img className={`card-grid__img ${image === "monkeydluffy.svg" ? monkey_img : 
                                        image === "nico.svg" ? nico_img : 
                                        image === "ace.svg" ? portgas_img : '' }`} src={`images/${image}`} alt=""/>
      <h3 className="character-card__name">{name}</h3>
    </div>
  )
}

export default CharacterCard;

// task10-vue/one-piece-site/src/components/cards/CharacterCard.vue
<template>
  <div class="character-card">
    <img class="card-grid__img" 
        :class="{'img--center' : image === '/images/monkeydluffy.svg', 
                 'img--nico' : image === '/images/nico.svg', 
                 'img--portgas' : image === '/images/ace.svg'}" :src=image alt=""/>
    <h3 class="character-card__name">{{name}}</h3>
  </div>
</template>


<script>
  export default {
    name : 'CharacterCard',
    props : {
      image:String,
      name:String
    }
  }
</script>
